#!/usr/bin/env python3
"""渲染 Nginx 受信 TLS 终结器部署合同，失败关闭于缺失/过宽/非法 CIDR。

输出文件由 deploy/docker-compose.yml 只读挂载到
/etc/nginx/trusted-proxies.conf；直接模式（无外部 TLS 终结器）只写入
geo 默认信任标志 0，使客户端提交的任何代理头都不会被接受。
"""

from __future__ import annotations

import argparse
import ipaddress
import os
import sys
import tempfile
from pathlib import Path

EXACT_IPV4_PREFIX = 32
EXACT_IPV6_PREFIX = 128


def _parse_cidrs(raw: str) -> list[ipaddress._BaseNetwork]:
    networks: list[ipaddress._BaseNetwork] = []
    for item in (part.strip() for part in raw.split(",")):
        if not item:
            continue
        try:
            network = ipaddress.ip_network(item, strict=True)
        except ValueError as error:
            raise ValueError(f"trusted proxy CIDR 无法解析: {item}") from error
        if network.prefixlen == 0:
            raise ValueError("trusted proxy CIDR 禁止为 0.0.0.0/0 或 ::/0")
        if network.version == 4 and network.prefixlen != EXACT_IPV4_PREFIX:
            raise ValueError(
                f"trusted proxy IPv4 必须是单一主机 /{EXACT_IPV4_PREFIX}: {item}"
            )
        if network.version == 6 and network.prefixlen != EXACT_IPV6_PREFIX:
            raise ValueError(
                f"trusted proxy IPv6 必须是单一主机 /{EXACT_IPV6_PREFIX}: {item}"
            )
        networks.append(network)
    return networks


def render(mode: str, cidrs: str) -> str:
    if mode not in {"0", "1"}:
        raise ValueError("SMS_EXTERNAL_TLS_MODE 必须是 0 或 1")
    if mode == "0":
        return (
            "# Generated by render_trusted_proxy_conf.py (direct mode).\n"
            "# Web Nginx 是最外层可信代理，不接受客户端代理头。\n"
            "geo $realip_remote_addr $sms_trusted_proxy {\n"
            "    default 0;\n"
            "}\n"
            "geo $realip_remote_addr $sms_plaintext_client_allowed {\n"
            "    default 1;\n"
            "}\n"
        )
    networks = _parse_cidrs(cidrs)
    if not networks:
        raise ValueError(
            "SMS_EXTERNAL_TLS_MODE=1 但未配置 SMS_TRUSTED_PROXY_CIDRS，拒绝启动"
        )
    lines = [
        "# Generated by render_trusted_proxy_conf.py (external TLS mode).",
        "# 仅这些精确代理主机可声明真实客户端 IP 与外层协议；",
        "# 多主机网段、0.0.0.0/0 与客户端可达网段均被拒绝。",
        "geo $realip_remote_addr $sms_trusted_proxy {",
        "    default 0;",
    ]
    for network in networks:
        lines.append(f"    {network} 1;")
    lines.append("}")
    lines.extend(
        [
            "geo $realip_remote_addr $sms_plaintext_client_allowed {",
            "    default 0;",
        ]
    )
    for network in networks:
        lines.append(f"    {network} 1;")
    lines.append("}")
    for network in networks:
        lines.append(f"set_real_ip_from {network};")
    lines.append("real_ip_header X-Forwarded-For;")
    lines.append("real_ip_recursive on;")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", required=True)
    parser.add_argument("--cidrs", default="")
    parser.add_argument("--output")
    parser.add_argument("--validate-only", action="store_true")
    arguments = parser.parse_args()
    try:
        content = render(arguments.mode, arguments.cidrs)
        if arguments.validate_only:
            return 0
        if arguments.output is None:
            parser.error("--output is required unless --validate-only is used")
        target = Path(arguments.output)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.parent.chmod(0o755)
        descriptor, temporary = tempfile.mkstemp(
            prefix=f".{target.name}.",
            dir=str(target.parent),
        )
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                handle.write(content)
            os.chmod(temporary, 0o644)
            os.replace(temporary, target)
        except BaseException:
            Path(temporary).unlink(missing_ok=True)
            raise
    except ValueError as error:
        print(f"render-trusted-proxy: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
