import { readFileSync } from "node:fs"
import { resolve } from "node:path"

const read = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8")
const css = read("src/styles/workspace.css")
const messageView = read("src/views/MessageView.vue")
const replyView = read("src/views/ReplyView.vue")
const auditView = read("src/views/AuditView.vue")
const userView = read("src/views/UserView.vue")
const configView = read("src/views/ConfigView.vue")
const opsView = read("src/views/OpsView.vue")
const reportView = read("src/views/ReportView.vue")
const blacklistView = read("src/views/BlacklistView.vue")
const sensitiveWordView = read("src/views/SensitiveWordView.vue")
const compactViews = ["CallbackView.vue"].map(
  (name) => read(`src/views/${name}`),
)
const approvalView = read("src/views/ApprovalView.vue")
const batchView = read("src/views/BatchView.vue")
const signView = read("src/views/SignView.vue")
const templateView = read("src/views/TemplateView.vue")

describe("全站筛选布局契约", () => {
  it("使用共享十二列网格与语义跨度", () => {
    expect(css).toMatch(/\.filter-grid\s*\{[^}]*display:\s*grid[^}]*repeat\(12,/s)
    for (const span of [2, 3, 4, 6]) {
      expect(css).toContain(`.filter-span-${span}`)
    }
    expect(css).toMatch(/\.filter-actions[^}]*align-self:\s*end/s)
  })

  it("中等宽度重排且手机端单列", () => {
    expect(css).toMatch(/@media \(max-width: 1100px\)[\s\S]*\.filter-grid/s)
    expect(css).toMatch(
      /@media \(max-width: 760px\)[\s\S]*\.filter-grid[^}]*grid-template-columns:\s*1fr/s,
    )
    expect(css).toMatch(
      /@media \(max-width: 760px\)[\s\S]*\.filter-grid \.el-form-item[^}]*min-width:\s*0/s,
    )
  })

  it("上行回复使用方案 A 单行检索条", () => {
    expect(replyView).toContain("reply-filter-bar")
    expect(replyView).toContain("reply-seg")
    expect(replyView).toContain("共 {{ total }} 条 · 每页 20")
    expect(replyView).toContain("未匹配到平台批次")
    expect(replyView).not.toContain("filter-grid")
    expect(replyView).not.toContain("filter-toolbar")
    expect(replyView).not.toContain("<el-segmented")
    expect(replyView).not.toContain("↗")
    expect(replyView).not.toContain("厂商未回传 customId")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("管理筛选遵循同一表单语义", () => {
    expect(auditView).toContain("filter-grid")
    expect(auditView).not.toMatch(/<el-form[^>]*\binline\b/)
  })

  it("用户与角色使用方案 A 单行检索条与身份台账", () => {
    expect(userView).toContain("user-filter-bar")
    expect(userView).toContain("user-seg")
    expect(userView).toContain("user-keyword")
    expect(userView).toContain("user-privacy")
    expect(userView).toContain("user-rules")
    expect(userView).toContain("共 {{ total }} 名用户 · 每页 20")
    expect(userView).toContain("本次操作已记入审计")
    expect(userView).not.toContain("filter-grid")
    expect(userView).not.toContain("filter-toolbar")
    expect(userView).not.toContain("<el-segmented")
    expect(userView).not.toContain("<el-card")
    expect(userView).not.toContain("user-pulse")
    expect(userView).not.toContain("account-rules")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(css).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules\s*\{[^}]*display:\s*flex/s)
  })

  it("系统参数使用方案 A 单行检索条与常驻规则条", () => {
    expect(configView).toContain("config-filter-bar")
    expect(configView).toContain("config-seg")
    expect(configView).toContain("config-keyword")
    expect(configView).toContain("config-privacy")
    expect(configView).toContain("config-rules")
    expect(configView).toContain("config-savebar")
    expect(configView).toContain("接口全量返回")
    expect(configView).toContain("共 {{ configs.length }} 项受控参数")
    expect(configView).toContain("本次操作已记入审计")
    expect(configView).not.toContain("filter-grid")
    expect(configView).not.toContain("filter-toolbar")
    expect(configView).not.toContain("<el-segmented")
    expect(configView).not.toContain("config-toolbar")
    expect(configView).not.toContain("config-restart-alert")
    expect(configView).not.toContain("config-heading-note")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("号码搜索使用方案 A 单行检索条", () => {
    expect(messageView).toContain("message-filter-bar")
    expect(messageView).toContain("message-seg")
    expect(messageView).toContain("message-badge")
    expect(messageView).toContain("共 {{ total }} 条 · 每页 20")
    expect(messageView).not.toContain("filter-grid")
    expect(messageView).not.toContain("filter-toolbar")
    expect(messageView).not.toContain("<el-segmented")
    expect(messageView).not.toContain("view-switch")
    expect(css).toMatch(/\.message-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.message-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("统计报表使用方案 A 单行工具条", () => {
    expect(reportView).toContain("report-filter-bar")
    expect(reportView).toContain("含明文手机号")
    expect(reportView).not.toContain("filter-grid")
    expect(reportView).not.toContain("<el-segmented")
    expect(css).toMatch(/\.report-filter-bar\s*\{[^}]*display:\s*flex/s)
  })

  it("轻量筛选统一使用紧凑工具栏", () => {
    for (const source of compactViews) expect(source).toContain("filter-toolbar")
    expect(css).toMatch(/\.filter-toolbar\s*\{[^}]*display:\s*flex[^}]*flex-wrap:\s*wrap/s)
  })

  it("批次列表使用方案 A 单行胶囊筛选条", () => {
    expect(batchView).toContain("batch-filter-bar")
    expect(batchView).toContain("batch-seg")
    expect(batchView).toContain("更多筛选")
    expect(batchView).not.toContain("filter-toolbar")
    expect(batchView).not.toContain("filter-grid")
    expect(batchView).not.toContain("<el-segmented")
    expect(batchView).not.toContain("query-total")
    expect(batchView).toContain("batch-scope")
    expect(batchView).toContain("batch-facts")
    expect(batchView).toContain("共 {{ total }} 个批次 · 每页 20")
    expect(css).toMatch(/\.batch-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.batch-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(css).toMatch(/\.compose\s*\{[^}]*height:\s*5px/s)
  })

  it("审批中心使用方案 A 单行胶囊筛选条", () => {
    expect(approvalView).toContain("approval-filter-bar")
    expect(approvalView).toContain('data-testid="approval-status-seg"')
    expect(approvalView).not.toContain("filter-toolbar")
    expect(approvalView).not.toContain("filter-grid")
    expect(approvalView).not.toContain("<el-segmented")
    expect(css).toMatch(/\.approval-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.approval-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("签名管理使用方案 A 单行胶囊工具条", () => {
    expect(signView).toContain("sign-filter-bar")
    expect(signView).toContain("sign-seg")
    expect(signView).toContain("接口全量返回 · 前端过滤")
    expect(signView).toContain("共 {{ filtered.length }} 个签名")
    expect(signView).toContain("读：operator / approver / admin · 写：admin")
    expect(signView).toContain("不可变更")
    expect(signView).not.toContain("filter-toolbar")
    expect(signView).not.toContain("filter-grid")
    expect(signView).not.toContain("<el-segmented")
    expect(signView).not.toContain("<el-card")
    expect(css).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("模板管理使用方案 A 单行胶囊工具条", () => {
    expect(templateView).toContain("template-filter-bar")
    expect(templateView).toContain("template-seg")
    expect(templateView).toContain("接口全量返回 · 前端过滤")
    expect(templateView).toContain("未送审（历史数据）")
    expect(templateView).toContain("共 {{ filtered.length }} 个模板")
    expect(templateView).toContain("读：operator / approver / admin · 写：operator / admin")
    expect(templateView).not.toContain("filter-toolbar")
    expect(templateView).not.toContain("filter-grid")
    expect(templateView).not.toContain("<el-segmented")
    expect(templateView).not.toContain("<el-card")
    expect(css).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(css).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{\s*align-items:\s*flex-start/s)
  })

  it("敏感词使用方案 A 单行检索条、词条墙与抽屉录入", () => {
    expect(sensitiveWordView).toContain("sensitive-filter-bar")
    expect(sensitiveWordView).toContain("sensitive-add-open")
    expect(sensitiveWordView).toContain("sensitive-drawer")
    expect(sensitiveWordView).toContain("sensitive-wall")
    expect(sensitiveWordView).toContain("sensitive-policy-seg")
    expect(sensitiveWordView).toContain("共 {{ total }} 条 · 每页 60")
    expect(sensitiveWordView).not.toContain("filter-toolbar")
    expect(sensitiveWordView).not.toContain("filter-grid")
    expect(sensitiveWordView).not.toContain("<el-segmented")
    expect(sensitiveWordView).not.toContain("<el-card")
    expect(sensitiveWordView).not.toContain("<el-table")
    expect(sensitiveWordView).not.toContain("governance-entry")
    expect(sensitiveWordView).not.toContain("sensitive-mobile-list")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(css).toMatch(/\.sensitive-wall\s*\{[^}]*display:\s*grid[^}]*auto-fill/s)
  })

  it("黑名单使用方案 A 单行检索条与抽屉录入", () => {
    expect(blacklistView).toContain("blacklist-filter-bar")
    expect(blacklistView).toContain("blacklist-seg")
    expect(blacklistView).toContain("blacklist-add-open")
    expect(blacklistView).toContain("blacklist-drawer")
    expect(blacklistView).toContain("共 {{ total }} 条 · 每页 20")
    expect(blacklistView).not.toContain("filter-toolbar")
    expect(blacklistView).not.toContain("filter-grid")
    expect(blacklistView).not.toContain("<el-segmented")
    expect(blacklistView).not.toContain("<el-card")
    expect(blacklistView).not.toContain("governance-entry")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("运维中心使用方案 A 单行检索条与常驻规则条", () => {
    expect(opsView).toContain("ops-filter-bar")
    expect(opsView).toContain("ops-seg")
    expect(opsView).toContain("ops-keyword")
    expect(opsView).toContain("ops-phone")
    expect(opsView).toContain("ops-dates")
    expect(opsView).toContain("ops-privacy")
    expect(opsView).toContain("ops-rules")
    expect(opsView).toContain("ops-results")
    expect(opsView).toContain("ops-confirm-dialog")
    expect(opsView).toContain("ops-confirm-audit")
    expect(opsView).toContain("共 {{ alertTotal }} 条 · 每页 20")
    expect(opsView).toContain("共 {{ rawTotal }} 条 · 每页 20")
    expect(opsView).toContain("共 {{ unmatchedTotal }} 条 · 每页 20")
    expect(opsView).toContain("共 {{ outboxTotal }} 条 · 每页 20")
    expect(opsView).toContain("本次操作已记入审计")
    expect(opsView).not.toContain("filter-grid")
    expect(opsView).not.toContain("filter-toolbar")
    expect(opsView).not.toContain("<el-tabs")
    expect(opsView).not.toContain("<el-card")
    expect(opsView).not.toContain("ops-workbench")
    expect(opsView).not.toContain("ops-filter-title")
    expect(css).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(css).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(css).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules\s*\{[^}]*display:\s*flex/s)
  })

  it("不再保留会覆盖共享栅格的旧筛选补丁", () => {
    expect(css).not.toContain("margin-bottom: -18px")
    expect(css).not.toMatch(
      /\.query-filter,\s*\.message-search,\s*\.audit-filter-card \.el-form\s*\{/s,
    )
  })
})
