import { readFileSync } from "node:fs"
import { resolve } from "node:path"

import { readWorkspaceCss } from "./workspace-css"

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8")

describe("青鸾 Console 17 屏结构保真", () => {
  it("路由覆盖交接包的 17 个业务屏", () => {
    const router = source("src/router/index.ts")
    const paths = [
      "/dashboard", "/send", "/batches", "/messages", "/approvals", "/ops",
      "/templates", "/signs", "/replies", "/apps", "/blacklist", "/sensitive-words",
      "/users", "/configs", "/reports", "/audit", "/login",
    ]
    for (const path of paths) expect(router).toContain(`path: "${path}"`)
  })

  it("人工发送使用两类卡并根据预检切换主动作", () => {
    const view = source("src/views/SendView.vue")
    const workspace = readWorkspaceCss()
    // verify 仅 API 渠道（PRD FR-00），Web 人工发送只展示通知/营销两张可选类别卡
    expect(view).toContain('data-testid="category-notice"')
    expect(view).toContain('data-testid="category-market"')
    expect(view).not.toContain('data-testid="category-verify"')
    expect(workspace).toMatch(/\.category-switch\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/s)
    expect(view).toContain("const submitLabel = computed")
    expect(view).toContain("提交审批")
    expect(view).toContain("立即发送")
    expect(view).toContain("send-preview precheck send-rail")
  })

  it("批次详情使用 560px 抽屉和结果构成区", () => {
    const view = source("src/views/BatchView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain('size="min(560px, 92vw)"')
    expect(view).toContain('class="batch-hero"')
    expect(view).toContain("构成非成功率")
    expect(view).toContain("batch-filter-bar")
    expect(view).toContain("batch-facts")
    expect(view).toContain("batch-scope")
    expect(view).toContain("共 {{ total }} 个批次 · 每页 20")
    expect(view).toContain("当前口径 ·")
    expect(view).toContain("class=\"batch-note\"")
    expect(view).not.toContain("batch-donut")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("退订语")
    expect(view).not.toContain("risk_first")
    expect(workspace).toMatch(/\.compose\s*\{[^}]*height:\s*5px/s)
    expect(workspace).toMatch(/\.batch-facts\s*\{[^}]*grid-template-columns:\s*1fr 1fr/s)
  })

  it("审批中心使用单一列表组件并按需解密正文", () => {
    const view = source("src/views/ApprovalView.vue")
    const list = source("src/components/ApprovalList.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("ApprovalList")
    expect(view).toContain("getApproval")
    expect(view).toContain("按需解密 · 本次查看已写敏感读审计")
    expect(view).toContain("approval-decide-box")
    expect(list).toContain('class="approval-rows"')
    // 待审批空态必须带面板框（approval-empty），与其它模块空表格观感一致
    expect(list).toContain('class="approval-empty"')
    expect(workspace).toMatch(/\.approval-empty\s*\{[^}]*background:\s*var\(--panel\)[^}]*border:\s*1px solid var\(--hair\)/s)
    expect(list).toContain("approval-cd")
    expect(list).toContain("本人提交 · 按规则回避")
    expect(list).toContain("approval-dest")
    expect(view).not.toContain("approval-mobile-list")
    expect(view).not.toContain("approval-queue")
    expect(view).toContain("approval-filter-bar")
    expect(view).toContain('size="min(560px, 92vw)"')
    expect(view).toContain("previewDecision")
    expect(view).not.toContain("已剔除")
    expect(view).not.toContain("近 7 天")
    expect(workspace).toMatch(/\.approval-row\s*\{[^}]*grid-template-columns:\s*86px[^}]*border-radius:\s*12px/s)
  })

  it("运维中心使用自定义页签条、单行检索条与常驻规则条", () => {
    const view = source("src/views/OpsView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("circuit-banner")
    expect(view).toContain("实时队列已恢复")
    expect(view).toContain("禁止自动重发")
    expect(view).toContain("ops-tabs")
    expect(view).toContain('role="tablist"')
    expect(view).toContain("ops-filter-bar")
    expect(view).toContain("ops-seg")
    expect(view).toContain("ops-rules")
    expect(view).toContain("ops-results")
    expect(view).toContain("ops-confirm-dialog")
    expect(view).toContain("ops-confirm-audit")
    expect(view).toContain("共 {{ alertTotal }} 条 · 每页 20")
    expect(view).toContain("本次操作已记入审计")
    expect(view).toContain('data-testid="ops-alert-level-seg"')
    expect(view).toContain('data-testid="ops-outbox-state"')
    expect(view).not.toContain('import "../styles/workspace.css"')
    expect(view).not.toContain("<el-tabs")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("ops-workbench")
    expect(view).not.toContain("ops-filter-title")
    expect(workspace).toMatch(/\.config-tabs,\s*\.ops-tabs\s*\{[^}]*overflow-x:\s*auto/s)
    // 告警面板题右侧的 .ops-seg 必须保持横向 flex：.ops-panel-title > div 的网格规则不得把它压成竖排
    expect(workspace).toMatch(/\.ops-alert-title\s*>\s*\.ops-seg\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules,\s*\.callback-rules,\s*\.security-daily-rules,\s*\.audit-rules\s*\{[^}]*display:\s*flex/s)
  })

  it("统计报表按方案 A 压成单行工具条、柱下图例和拆列明细", () => {
    const view = source("src/views/ReportView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("report-filter-bar")
    expect(view).toContain("含明文手机号")
    expect(view).toContain("未知不入分母")
    expect(view).toContain('label="周期"')
    expect(view).toContain('label="送达"')
    expect(view).toContain('label="失败"')
    expect(view).toContain('label="未知"')
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("周期起始")
    expect(view).not.toContain("长短信主要来自营销类模板")
    expect(workspace).toMatch(/\.report-trend-chart\s*\{[^}]*min-height:\s*170px/s)
    expect(workspace).toMatch(/\.report-kpi strong\s*\{[^}]*font-size:\s*26px/s)
    // 结果构成图例行不得复用裸类名 compose：批次页 .compose 横条组件（height:5px; overflow:hidden）会把它裁到只剩一条缝
    expect(view).not.toContain('class="kpi-kv compose"')
    expect(view).toContain('class="kpi-kv compose-shares"')
    expect(workspace).toMatch(/\.kpi-kv\.compose-shares\s*\{[^}]*justify-content:\s*space-between/s)
    expect(workspace).toMatch(/\.export-strip\s*\{\s*display:\s*flex;[\s\S]*?border-radius:\s*10px/)
  })

  it("号码搜索使用单行检索条和常驻徽标条", () => {
    const view = source("src/views/MessageView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("message-filter-bar")
    expect(view).toContain("message-badge")
    expect(view).toContain("message-phone-decrypt")
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain("↩ 用户回复")
    expect(view).not.toContain("view-switch")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("已入回复查询")
    expect(view).not.toContain("在途")
    expect(workspace).toMatch(/\.message-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.message-badge\s*\{[^}]*border-radius:\s*12px/s)
  })

  it("上行回复使用单行检索条和密表格", () => {
    const view = source("src/views/ReplyView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("reply-filter-bar")
    expect(view).toContain("reply-seg")
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain("未匹配到平台批次")
    expect(view).toContain("已加入退订黑名单 · 本次操作已记入审计")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("↗")
    expect(view).not.toContain("厂商未回传 customId")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar,\s*\.callback-filter-bar,\s*\.audit-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg,\s*\.callback-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("签名管理使用单行胶囊工具条和密表格", () => {
    const view = source("src/views/SignView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("sign-filter-bar")
    expect(view).toContain("sign-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain("共 {{ filtered.length }} 个签名")
    expect(view).toContain("读：operator / approver / admin · 写：admin")
    expect(view).toContain("签名已删除 · 本次操作已记入审计")
    expect(view).toContain("sign-content-block")
    expect(view).toContain("sign-fact-grid")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("drawer-intro")
    expect(workspace).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.sign-heading p:not\(\.eyebrow\)[\s\S]*font-size:\s*11px/s)
  })

  it("模板管理使用单行胶囊工具条和密表格", () => {
    const view = source("src/views/TemplateView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("template-filter-bar")
    expect(view).toContain("template-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain("未送审（历史数据）")
    expect(view).toContain("共 {{ filtered.length }} 个模板")
    expect(view).toContain("读：operator / approver / admin · 写：operator / admin")
    expect(view).toContain("模板已删除 · 本次操作已记入审计")
    expect(view).toContain("template-content-block")
    expect(view).toContain("template-fact-grid")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("占位与变量必须从 1")
    expect(workspace).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.template-heading p:not\(\.eyebrow\)[\s\S]*font-size:\s*11px/s)
  })

  it("应用管理使用单行筛选条和密钥状态账本表格", () => {
    const view = source("src/views/AppManagementView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("apps-filter-bar")
    expect(view).toContain("apps-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain('data-testid="app-table"')
    expect(view).toContain("apps-table")
    expect(view).toContain("apps-key-tag")
    expect(view).toContain("旧 Key 宽限 · 余")
    expect(view).toContain("单 Key 运行")
    expect(view).toContain("已随停用吊销")
    expect(view).toContain("keyGraceHours")
    expect(view).toContain("共 {{ filtered.length }} 个应用")
    expect(view).toContain("读写：admin · 今日消耗来自 stat_daily 联查")
    expect(view).not.toContain("app-card-grid")
    expect(view).not.toContain("managed-app-card")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(workspace).toMatch(/\.apps-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.apps-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.apps-quota-bar\s*\{[^}]*height:\s*5px/s)
  })

  it("用户与角色使用单行检索条和身份台账抽屉", () => {
    const view = source("src/views/UserView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("user-filter-bar")
    expect(view).toContain("user-seg")
    expect(view).toContain("user-rules")
    expect(view).toContain('data-testid="user-provider-seg"')
    expect(view).toContain('data-testid="user-role-seg"')
    expect(view).toContain('data-testid="user-status-seg"')
    expect(view).toContain('data-testid="create-precheck"')
    expect(view).toContain("user-drawer-head")
    expect(view).toContain("共 {{ total }} 名用户 · 每页 20")
    expect(view).toContain("本次操作已记入审计")
    expect(view).toContain("security_version")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("user-pulse")
    expect(view).not.toContain("account-rules")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar,\s*\.callback-filter-bar,\s*\.audit-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg,\s*\.callback-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules,\s*\.callback-rules,\s*\.security-daily-rules,\s*\.audit-rules\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.user-heading p:not\(\.eyebrow\)[\s\S]*?font-size:\s*11px/s)
  })

  it("系统参数使用单行检索条、常驻规则条与分组参数网格", () => {
    const view = source("src/views/ConfigView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("config-filter-bar")
    expect(view).toContain("config-seg")
    expect(view).toContain('data-testid="config-group-seg"')
    expect(view).toContain("config-rules")
    expect(view).toContain("config-savebar")
    expect(view).toContain("共 {{ configs.length }} 项受控参数")
    expect(view).toContain("config-confirm-dialog")
    expect(view).toContain("config-confirm-audit")
    expect(view).toContain("本次操作已记入审计")
    expect(view).not.toContain('import "../styles/workspace.css"')
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("config-toolbar")
    expect(view).not.toContain("config-restart-alert")
    expect(view).not.toContain("config-heading-note")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar,\s*\.callback-filter-bar,\s*\.audit-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg,\s*\.callback-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.config-group\s*\{[^}]*border-radius:\s*12px/s)
  })

  it("回调任务使用单行检索条、常驻规则条与详情抽屉", () => {
    const view = source("src/views/CallbackView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("callback-filter-bar")
    expect(view).toContain("callback-seg")
    expect(view).toContain("callback-rules")
    expect(view).toContain('data-testid="callback-status-seg"')
    expect(view).toContain('data-testid="callback-event-seg"')
    expect(view).toContain('data-testid="callback-app-filter"')
    expect(view).toContain('data-testid="callback-batch-filter"')
    expect(view).toContain("callback-drawer")
    expect(view).toContain("callback-confirm-dialog")
    expect(view).toContain("callback-confirm-audit")
    expect(view).toContain("共 {{ total }} 项 · 每页 20 · dead 总计 {{ deadTotal }}")
    expect(view).toContain("本次操作已记入审计")
    expect(view).not.toContain('import "../styles/workspace.css"')
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("callback-filter-card")
    expect(view).not.toContain("callback-table-card")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar,\s*\.callback-filter-bar,\s*\.audit-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg,\s*\.config-seg,\s*\.ops-seg,\s*\.callback-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules,\s*\.callback-rules,\s*\.security-daily-rules,\s*\.audit-rules\s*\{[^}]*display:\s*flex/s)
  })

  it("安全日报使用页级紧凑单行检索条、常驻规则条与事实带台账", () => {
    const view = source("src/views/SecurityDailyView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("security-daily-filter-bar")
    expect(view).toContain("security-daily-seg")
    expect(view).toContain("security-daily-fld")
    expect(view).toContain("security-daily-filter-go")
    expect(view).toContain("security-daily-privacy")
    expect(view).toContain("security-daily-rules")
    expect(view).toContain("security-daily-results")
    expect(view).toContain("security-daily-overview")
    expect(view).toContain("security-daily-state")
    expect(view).toContain("security-daily-facts")
    expect(view).toContain('data-testid="security-daily-status-seg"')
    expect(view).toContain('data-testid="security-daily-generation-seg"')
    expect(view).toContain('data-testid="security-daily-delivery-seg"')
    expect(view).toContain('data-testid="security-daily-date-from"')
    expect(view).toContain('data-testid="security-daily-date-to"')
    expect(view).toContain('data-testid="security-daily-search"')
    expect(view).toContain('data-testid="security-daily-reset"')
    expect(view).toContain("security-daily-confirm-dialog")
    expect(view).toContain("security-daily-confirm-audit")
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain("本次操作已记入审计")
    expect(view).not.toContain('import "../styles/workspace.css"')
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("security-daily-filters")
    expect(view).not.toContain("security-daily-state-card")
    expect(view).not.toContain("card-heading")
    // 概览两段式：状态横条（右侧下次调度 mono em）+ 8 格事实 flex 横排带
    expect(view).toMatch(/<div class="security-daily-state">[\s\S]*<em v-if="overview\.next_scheduled_at">[\s\S]*<dl class="security-daily-facts">/)
    expect(workspace).toMatch(/\.security-daily-state\s*\{[^}]*display:\s*flex[^}]*linear-gradient\(90deg/s)
    expect(workspace).toMatch(/\.security-daily-facts\s*\{[^}]*display:\s*flex[^}]*flex-wrap:\s*wrap/s)
    expect(workspace).toMatch(/\.security-daily-facts > div\s*\{[^}]*min-width:\s*150px/s)
    // 标签内联 + 查询/重置同行 + 说明细字在条下一行
    expect(view).toMatch(/<form class="security-daily-filter-bar"[\s\S]*<div class="security-daily-filter-go">[\s\S]*<\/form>\s*<p class="security-daily-privacy">/)
    expect(workspace).toMatch(/\.security-daily-filter-bar\s*\{[^}]*display:\s*flex[^}]*flex-wrap:\s*wrap/s)
    expect(workspace).toMatch(/\.security-daily-fld\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center/s)
    expect(workspace).toMatch(/\.security-daily-fld > span\s*\{[^}]*white-space:\s*nowrap/s)
    expect(workspace).toMatch(/\.security-daily-date\s*\{[^}]*width:\s*112px/s)
    expect(workspace).toMatch(/\.security-daily-seg\s*\{[^}]*height:\s*30px/s)
    expect(workspace).toMatch(/\.security-daily-filter-go\s*\{[^}]*margin-left:\s*auto/s)
    expect(workspace).toMatch(/\.security-daily-privacy\s*\{[^}]*font-size:\s*10\.5px/s)
    // 检索条不再并入 reply-* 共享尺寸组；规则条仍与 user-rules 同组
    expect(workspace).not.toMatch(/\.callback-filter-bar,\s*\.security-daily-filter-bar/)
    expect(workspace).not.toMatch(/\.callback-seg,\s*\.security-daily-seg/)
    expect(workspace).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules,\s*\.callback-rules,\s*\.security-daily-rules,\s*\.audit-rules\s*\{[^}]*display:\s*flex/s)
    // 760px 断点整体纵排
    expect(workspace).toMatch(/@media \(max-width: 760px\)[\s\S]*\.security-daily-filter-bar\s*\{\s*flex-direction:\s*column/s)
  })

  it("审计日志使用单行检索条、常驻规则条与载荷差异抽屉", () => {
    const view = source("src/views/AuditView.vue")
    const workspace = readWorkspaceCss()
    expect(view).toContain("audit-filter-bar")
    expect(view).toContain("audit-fld")
    expect(view).toContain("audit-keyword")
    expect(view).toContain("audit-dates")
    expect(view).toContain("audit-privacy")
    expect(view).toContain("audit-rules")
    expect(view).toContain("audit-results")
    expect(view).toContain("audit-pagination")
    expect(view).toContain("audit-diff")
    expect(view).toContain("audit-mobile-list")
    expect(view).toContain('data-testid="audit-actor"')
    expect(view).toContain('data-testid="audit-action"')
    expect(view).toContain('data-testid="audit-object-type"')
    expect(view).toContain('data-testid="audit-object-id"')
    expect(view).toContain('data-testid="audit-time-range"')
    expect(view).toContain('data-testid="audit-more-filters"')
    expect(view).toContain('data-testid="audit-account-id"')
    expect(view).toContain('data-testid="audit-correlation-id"')
    expect(view).toContain('data-testid="audit-reset"')
    expect(view).toContain('data-testid="audit-clear-filters"')
    expect(view).toContain('data-testid="audit-copy-correlation"')
    expect(view).toContain('data-testid="audit-trace-correlation"')
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain('size="min(560px, 92vw)"')
    expect(view).not.toContain('import "../styles/workspace.css"')
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("audit-filter-card")
    expect(view).not.toContain("audit-result-title")
    // 检索条/结果面板/分页并入 reply-* 共享组；规则条与 user-rules 同组；更多筛选触发器与 batch-more 同组
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar,\s*\.config-filter-bar,\s*\.ops-filter-bar,\s*\.callback-filter-bar,\s*\.audit-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-results,\s*\.blacklist-results,\s*\.sensitive-results,\s*\.user-results,\s*\.ops-results,\s*\.callback-results,\s*\.security-daily-results,\s*\.audit-results\s*\{/s)
    expect(workspace).toMatch(/\.user-rules,\s*\.config-rules,\s*\.ops-rules,\s*\.callback-rules,\s*\.security-daily-rules,\s*\.audit-rules\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.batch-more-trigger,\s*\.audit-more-trigger\s*\{/s)
    expect(workspace).toMatch(/\.reply-pagination,\s*\.blacklist-pagination,\s*\.sensitive-pagination,\s*\.user-pagination,\s*\.ops-pagination,\s*\.callback-pagination,\s*\.security-daily-pagination,\s*\.audit-pagination\s*\{/s)
    expect(workspace).not.toMatch(/\.filter-grid\s*\{/s)
    expect(workspace).not.toMatch(/\.audit-filter-card\s*\{/s)
    // 760px 断点保留表格↔卡片双渲染与差异格纵排折叠
    expect(workspace).toMatch(/@media \(max-width: 760px\)[\s\S]*\.audit-table\s*\{[^}]*display:\s*none/s)
    expect(workspace).toMatch(/@media \(max-width: 760px\)[\s\S]*\.audit-mobile-list\s*\{[^}]*display:\s*grid/s)
    expect(workspace).toMatch(/@media \(max-width: 760px\)[\s\S]*\.audit-diff-row\s*\{[^}]*grid-template-columns:\s*1fr/s)
  })
})
