import { readFileSync } from "node:fs"
import { resolve } from "node:path"

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8")

describe("青鸾 Console 17 屏结构保真", () => {
  it("路由覆盖交接包的 17 个业务屏", () => {
    const router = source("src/router/index.ts")
    const paths = [
      "/dashboard", "/send", "/batches", "/messages", "/approvals", "/ops",
      "/templates", "/signs", "/replies", "/apps", "/blacklist", "/sensitive-words",
      "/users", "/configs", "/reports", "/audit", "/login",
    ]
    for (const path of paths) expect(router).toContain(`path: "${path}"`)
  })

  it("人工发送使用三类卡并根据预检切换主动作", () => {
    const view = source("src/views/SendView.vue")
    expect(view).toContain('data-testid="category-verify"')
    expect(view).toMatch(/data-testid="category-verify"[\s\S]*?disabled/)
    expect(view).toContain("const submitLabel = computed")
    expect(view).toContain("提交审批")
    expect(view).toContain("立即发送")
    expect(view).toContain("send-preview precheck send-rail")
  })

  it("批次详情使用 560px 抽屉和结果构成区", () => {
    const view = source("src/views/BatchView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain('size="min(560px, 92vw)"')
    expect(view).toContain('class="batch-hero"')
    expect(view).toContain("构成非成功率")
    expect(view).toContain("batch-filter-bar")
    expect(view).toContain("batch-facts")
    expect(view).toContain("batch-scope")
    expect(view).toContain("共 {{ total }} 个批次 · 每页 20")
    expect(view).toContain("当前口径 ·")
    expect(view).toContain("class=\"batch-note\"")
    expect(view).not.toContain("batch-donut")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("退订语")
    expect(view).not.toContain("risk_first")
    expect(workspace).toMatch(/\.compose\s*\{[^}]*height:\s*5px/s)
    expect(workspace).toMatch(/\.batch-facts\s*\{[^}]*grid-template-columns:\s*1fr 1fr/s)
  })

  it("审批中心使用单一列表组件并按需解密正文", () => {
    const view = source("src/views/ApprovalView.vue")
    const list = source("src/components/ApprovalList.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("ApprovalList")
    expect(view).toContain("getApproval")
    expect(view).toContain("按需解密 · 本次查看已写敏感读审计")
    expect(view).toContain("approval-decide-box")
    expect(list).toContain('class="approval-rows"')
    expect(list).toContain("approval-cd")
    expect(list).toContain("本人提交 · 按规则回避")
    expect(list).toContain("approval-dest")
    expect(view).not.toContain("approval-mobile-list")
    expect(view).not.toContain("approval-queue")
    expect(view).toContain("approval-filter-bar")
    expect(view).toContain('size="min(560px, 92vw)"')
    expect(view).toContain("previewDecision")
    expect(view).not.toContain("已剔除")
    expect(view).not.toContain("近 7 天")
    expect(workspace).toMatch(/\.approval-row\s*\{[^}]*grid-template-columns:\s*86px[^}]*border-radius:\s*12px/s)
  })

  it("运维中心在标签页上方呈现熔断恢复横幅", () => {
    const view = source("src/views/OpsView.vue")
    expect(view).toContain("circuit-banner")
    expect(view).toContain("实时队列已恢复")
    expect(view).toContain("禁止自动重发")
  })

  it("统计报表按方案 A 压成单行工具条、柱下图例和拆列明细", () => {
    const view = source("src/views/ReportView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("report-filter-bar")
    expect(view).toContain("含明文手机号")
    expect(view).toContain("unknown 不入分母")
    expect(view).toContain('label="周期"')
    expect(view).toContain('label="送达"')
    expect(view).toContain('label="失败"')
    expect(view).toContain('label="未知"')
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("周期起始")
    expect(view).not.toContain("长短信主要来自营销类模板")
    expect(workspace).toMatch(/\.report-trend-chart\s*\{[^}]*min-height:\s*170px/s)
    expect(workspace).toMatch(/\.report-kpi strong\s*\{[^}]*font-size:\s*26px/s)
    expect(workspace).toMatch(/\.export-strip\s*\{\s*display:\s*flex;[\s\S]*?border-radius:\s*10px/)
  })

  it("号码搜索使用单行检索条和常驻徽标条", () => {
    const view = source("src/views/MessageView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("message-filter-bar")
    expect(view).toContain("message-badge")
    expect(view).toContain("message-phone-decrypt")
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain("↩ 用户回复")
    expect(view).not.toContain("view-switch")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("已入回复查询")
    expect(view).not.toContain("在途")
    expect(workspace).toMatch(/\.message-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.message-badge\s*\{[^}]*border-radius:\s*12px/s)
  })

  it("上行回复使用单行检索条和密表格", () => {
    const view = source("src/views/ReplyView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("reply-filter-bar")
    expect(view).toContain("reply-seg")
    expect(view).toContain("共 {{ total }} 条 · 每页 20")
    expect(view).toContain("未匹配到平台批次")
    expect(view).toContain("已加入退订黑名单 · 本次操作已记入审计")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("↗")
    expect(view).not.toContain("厂商未回传 customId")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg\s*\{[^}]*border-radius:\s*7px/s)
  })

  it("签名管理使用单行胶囊工具条和密表格", () => {
    const view = source("src/views/SignView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("sign-filter-bar")
    expect(view).toContain("sign-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain("共 {{ filtered.length }} 个签名")
    expect(view).toContain("读：operator / approver / admin · 写：admin")
    expect(view).toContain("签名已删除 · 本次操作已记入审计")
    expect(view).toContain("sign-content-block")
    expect(view).toContain("sign-fact-grid")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("drawer-intro")
    expect(workspace).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.sign-heading p:not\(\.eyebrow\)[\s\S]*font-size:\s*11px/s)
  })

  it("模板管理使用单行胶囊工具条和密表格", () => {
    const view = source("src/views/TemplateView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("template-filter-bar")
    expect(view).toContain("template-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain("未送审（历史数据）")
    expect(view).toContain("共 {{ filtered.length }} 个模板")
    expect(view).toContain("读：operator / approver / admin · 写：operator / admin")
    expect(view).toContain("模板已删除 · 本次操作已记入审计")
    expect(view).toContain("template-content-block")
    expect(view).toContain("template-fact-grid")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("占位与变量必须从 1")
    expect(workspace).toMatch(/\.template-filter-bar,\s*\.sign-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.template-seg,\s*\.sign-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.template-heading p:not\(\.eyebrow\)[\s\S]*font-size:\s*11px/s)
  })

  it("应用管理使用单行筛选条和密钥状态账本表格", () => {
    const view = source("src/views/AppManagementView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("apps-filter-bar")
    expect(view).toContain("apps-seg")
    expect(view).toContain("接口全量返回 · 前端过滤")
    expect(view).toContain('data-testid="app-table"')
    expect(view).toContain("apps-table")
    expect(view).toContain("apps-key-tag")
    expect(view).toContain("旧 Key 宽限 · 余")
    expect(view).toContain("单 Key 运行")
    expect(view).toContain("已随停用吊销")
    expect(view).toContain("keyGraceHours")
    expect(view).toContain("共 {{ filtered.length }} 个应用")
    expect(view).toContain("读写：admin · 今日消耗来自 stat_daily 联查")
    expect(view).not.toContain("app-card-grid")
    expect(view).not.toContain("managed-app-card")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(workspace).toMatch(/\.apps-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.apps-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.apps-quota-bar\s*\{[^}]*height:\s*5px/s)
  })

  it("用户与角色使用单行检索条和身份台账抽屉", () => {
    const view = source("src/views/UserView.vue")
    const workspace = source("src/styles/workspace.css")
    expect(view).toContain("user-filter-bar")
    expect(view).toContain("user-seg")
    expect(view).toContain("user-rules")
    expect(view).toContain('data-testid="user-provider-seg"')
    expect(view).toContain('data-testid="user-role-seg"')
    expect(view).toContain('data-testid="user-status-seg"')
    expect(view).toContain('data-testid="create-precheck"')
    expect(view).toContain("user-drawer-head")
    expect(view).toContain("共 {{ total }} 名用户 · 每页 20")
    expect(view).toContain("本次操作已记入审计")
    expect(view).toContain("security_version")
    expect(view).not.toContain("<el-segmented")
    expect(view).not.toContain("filter-grid")
    expect(view).not.toContain("filter-toolbar")
    expect(view).not.toContain("<el-card")
    expect(view).not.toContain("user-pulse")
    expect(view).not.toContain("account-rules")
    expect(workspace).toMatch(/\.reply-filter-bar,\s*\.blacklist-filter-bar,\s*\.sensitive-filter-bar,\s*\.user-filter-bar\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.reply-seg,\s*\.blacklist-seg,\s*\.sensitive-policy-seg,\s*\.user-seg\s*\{[^}]*border-radius:\s*7px/s)
    expect(workspace).toMatch(/\.user-rules\s*\{[^}]*display:\s*flex/s)
    expect(workspace).toMatch(/\.user-heading p:not\(\.eyebrow\)[\s\S]*?font-size:\s*11px/s)
  })
})
